var json_PuntosPartidodeMerlo_3 = {
"type": "FeatureCollection",
"name": "PuntosPartidodeMerlo_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "733", "osm_id": null, "osm_way_id": "286203223", "name": "El Fogon de Papi", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"cuisine\"=>\"regional\"" }, "geometry": { "type": "Point", "coordinates": [ -58.72074974846506, -34.713034523886655 ] } },
{ "type": "Feature", "properties": { "fid": "1062", "osm_id": null, "osm_way_id": "467289398", "name": "Benjamín", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Avenida del Libertador\"" }, "geometry": { "type": "Point", "coordinates": [ -58.724809268679209, -34.671634332413809 ] } },
{ "type": "Feature", "properties": { "fid": "1154", "osm_id": null, "osm_way_id": "467522673", "name": "Cheka", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:housenumber\"=>\"430\",\"addr:postcode\"=>\"1722\",\"addr:street\"=>\"Juncal\"" }, "geometry": { "type": "Point", "coordinates": [ -58.726673588741711, -34.669974669302611 ] } },
{ "type": "Feature", "properties": { "fid": "1180", "osm_id": null, "osm_way_id": "468067394", "name": "Mandu K", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"cuisine\"=>\"pizza\"" }, "geometry": { "type": "Point", "coordinates": [ -58.700717548561791, -34.665524322254022 ] } },
{ "type": "Feature", "properties": { "fid": "1189", "osm_id": null, "osm_way_id": "468492182", "name": "Texas", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Sarandi\"" }, "geometry": { "type": "Point", "coordinates": [ -58.723422199999987, -34.67112775 ] } },
{ "type": "Feature", "properties": { "fid": "1232", "osm_id": null, "osm_way_id": "468556667", "name": "Parrilla Rotisería", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Balbastro\"" }, "geometry": { "type": "Point", "coordinates": [ -58.732879743730322, -34.684963335095802 ] } },
{ "type": "Feature", "properties": { "fid": "1269", "osm_id": null, "osm_way_id": "468560790", "name": "Darogado", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Avenida Presidente Juan Domingo Perón\"" }, "geometry": { "type": "Point", "coordinates": [ -58.72863032749828, -34.664988978639862 ] } },
{ "type": "Feature", "properties": { "fid": "1315", "osm_id": null, "osm_way_id": "468566124", "name": "Locos X La Pizza", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:street\"=>\"Juncal\",\"cuisine\"=>\"pizza\"" }, "geometry": { "type": "Point", "coordinates": [ -58.725083995576171, -34.672430829387537 ] } },
{ "type": "Feature", "properties": { "fid": "1345", "osm_id": null, "osm_way_id": "468764381", "name": "El Trebol Pool", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": "billiards", "tourism": null, "other_tags": "\"addr:street\"=>\"Avenida Presidente Juan Domingo Perón\"" }, "geometry": { "type": "Point", "coordinates": [ -58.730077422783076, -34.665268018978679 ] } },
{ "type": "Feature", "properties": { "fid": "1357", "osm_id": null, "osm_way_id": "468765542", "name": "Palpan", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Jose Bettinoti\"" }, "geometry": { "type": "Point", "coordinates": [ -58.751567035219502, -34.688192527621567 ] } },
{ "type": "Feature", "properties": { "fid": "1359", "osm_id": null, "osm_way_id": "468765550", "name": "La Posta", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:street\"=>\"Jose Bettinoti\"" }, "geometry": { "type": "Point", "coordinates": [ -58.751989103919186, -34.687861334047881 ] } },
{ "type": "Feature", "properties": { "fid": "1363", "osm_id": null, "osm_way_id": "468768409", "name": "Castetner", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": null }, "geometry": { "type": "Point", "coordinates": [ -58.728658397159229, -34.665272791152219 ] } },
{ "type": "Feature", "properties": { "fid": "1387", "osm_id": null, "osm_way_id": "468779316", "name": "Las Chicas", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": null }, "geometry": { "type": "Point", "coordinates": [ -58.752214797846285, -34.687673956921522 ] } },
{ "type": "Feature", "properties": { "fid": "1401", "osm_id": null, "osm_way_id": "468786784", "name": null, "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"cuisine\"=>\"barbecue\"" }, "geometry": { "type": "Point", "coordinates": [ -58.701328498715156, -34.666479219236955 ] } },
{ "type": "Feature", "properties": { "fid": "1423", "osm_id": null, "osm_way_id": "468800186", "name": "Pollo Matambre Pescado", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": null }, "geometry": { "type": "Point", "coordinates": [ -58.763174800626537, -34.677069001088121 ] } },
{ "type": "Feature", "properties": { "fid": "1460", "osm_id": null, "osm_way_id": "468842530", "name": "Punto Norte", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"Merlo Norte\",\"addr:street\"=>\"Presidente Héctor Campora\"" }, "geometry": { "type": "Point", "coordinates": [ -58.724920560272778, -34.664025289951901 ] } },
{ "type": "Feature", "properties": { "fid": "1581", "osm_id": null, "osm_way_id": "614348951", "name": "CODE Lounge Bar", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:housenumber\"=>\"412\",\"addr:postcode\"=>\"1722\",\"addr:street\"=>\"Juncal\",\"opening_hours\"=>\"Mo-Su 18:00-01:00\"" }, "geometry": { "type": "Point", "coordinates": [ -58.726495298860854, -34.670153860231522 ] } },
{ "type": "Feature", "properties": { "fid": "1583", "osm_id": null, "osm_way_id": "614348963", "name": "Pizzeria & Rotiseria Manolo", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:housenumber\"=>\"802\",\"addr:postcode\"=>\"1722\",\"addr:street\"=>\"Victoriano Loza\",\"phone\"=>\"0220 485-9494\",\"takeaway\"=>\"only\"" }, "geometry": { "type": "Point", "coordinates": [ -58.719693736575529, -34.669320985050923 ] } },
{ "type": "Feature", "properties": { "fid": "1589", "osm_id": null, "osm_way_id": "614348985", "name": "Algo Nuevo", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"San Antonio de Padua\",\"addr:housenumber\"=>\"398\",\"addr:postcode\"=>\"1718\",\"addr:street\"=>\"Intendente Mendiluce\",\"outdoor_seating\"=>\"yes\",\"phone\"=>\"0220 483-6162\",\"takeaway\"=>\"yes\",\"website\"=>\"http:\/\/www.algonuevorestoran.com\/\"" }, "geometry": { "type": "Point", "coordinates": [ -58.698629058972521, -34.670717800715835 ] } },
{ "type": "Feature", "properties": { "fid": "1600", "osm_id": null, "osm_way_id": "614349031", "name": "La Fragata", "type": null, "aeroway": null, "amenity": "restaurant", "admin_level": null, "barrier": null, "boundary": null, "building": "yes", "craft": null, "geological": null, "historic": null, "land_area": null, "landuse": null, "leisure": null, "man_made": null, "military": null, "natural": null, "office": null, "place": null, "shop": null, "sport": null, "tourism": null, "other_tags": "\"addr:city\"=>\"San Antonio de Padua\",\"addr:housenumber\"=>\"98\",\"addr:postcode\"=>\"1718\",\"addr:street\"=>\"Noguera\",\"outdoor_seating\"=>\"yes\",\"phone\"=>\"0220 483-3880\",\"takeaway\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ -58.698659892090028, -34.66690113429835 ] } }
]
}
