var json_PuntosPartidodeMerlo_2 = {
"type": "FeatureCollection",
"name": "PuntosPartidodeMerlo_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "209", "osm_id": "2147026739", "name": "Los Alpes", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7272286, -34.6651243 ] ] } },
{ "type": "Feature", "properties": { "fid": "255", "osm_id": "2253879175", "name": "Piccolo", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.6996317, -34.666061 ] ] } },
{ "type": "Feature", "properties": { "fid": "1086", "osm_id": "4015812760", "name": "La Farola Express", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:housenumber\"=>\"699\",\"addr:postcode\"=>\"1722\",\"addr:street\"=>\"Suipacha\",\"amenity\"=>\"restaurant\",\"phone\"=>\"0220 483-5627\",\"takeaway\"=>\"yes\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7278425, -34.6667257 ] ] } },
{ "type": "Feature", "properties": { "fid": "1087", "osm_id": "4015812761", "name": "Camila", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7266021, -34.6694536 ] ] } },
{ "type": "Feature", "properties": { "fid": "1089", "osm_id": "4015812769", "name": "Lo de carlitos", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:postcode\"=>\"1722\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.723808, -34.6721972 ] ] } },
{ "type": "Feature", "properties": { "fid": "1101", "osm_id": "4015814540", "name": "Astur", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\",\"takeaway\"=>\"yes\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.723468, -34.6731695 ] ] } },
{ "type": "Feature", "properties": { "fid": "1106", "osm_id": "4015814561", "name": "Parrilla Ayres De Campo", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7324658, -34.6433498 ] ] } },
{ "type": "Feature", "properties": { "fid": "1283", "osm_id": "4621134697", "name": "Ya Voy Pizzeria", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.6769112, -34.6814571 ] ] } },
{ "type": "Feature", "properties": { "fid": "1294", "osm_id": "4621405309", "name": "Fábrica de Pizzas", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7273994, -34.6634154 ] ] } },
{ "type": "Feature", "properties": { "fid": "1298", "osm_id": "4622716430", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"amenity\"=>\"restaurant\",\"cuisine\"=>\"pizza\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7261069, -34.6490319 ] ] } },
{ "type": "Feature", "properties": { "fid": "1313", "osm_id": "4630255045", "name": "Pizzarella", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:street\"=>\"Sarandi\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7237491, -34.6705744 ] ] } },
{ "type": "Feature", "properties": { "fid": "1328", "osm_id": "4630312732", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:street\"=>\"Juncal\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7257595, -34.6716524 ] ] } },
{ "type": "Feature", "properties": { "fid": "1373", "osm_id": "4630879515", "name": "Pizza & Coffee Pepper", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7267923, -34.6664024 ] ] } },
{ "type": "Feature", "properties": { "fid": "1405", "osm_id": "4630895700", "name": "Pizzarium", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.725556, -34.6715741 ] ] } },
{ "type": "Feature", "properties": { "fid": "1407", "osm_id": "4630992218", "name": "Las Palmeras", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:street\"=>\"Avenida Argentina\",\"amenity\"=>\"restaurant\",\"cuisine\"=>\"pizza\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7244143, -34.6743934 ] ] } },
{ "type": "Feature", "properties": { "fid": "1412", "osm_id": "4630992246", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:street\"=>\"Oro\",\"amenity\"=>\"restaurant\",\"cuisine\"=>\"pizza\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7271032, -34.6791663 ] ] } },
{ "type": "Feature", "properties": { "fid": "1462", "osm_id": "4633248954", "name": "Piú", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo Norte\",\"addr:street\"=>\"Presidente Héctor Campora\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7252012, -34.6639064 ] ] } },
{ "type": "Feature", "properties": { "fid": "1478", "osm_id": "4633502035", "name": "Empanadas de Diez", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:street\"=>\"Avenida Hipólito Yrigoyen\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7266773, -34.6615445 ] ] } },
{ "type": "Feature", "properties": { "fid": "1494", "osm_id": "4858736864", "name": "Renatta", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7017331, -34.6663399 ] ] } },
{ "type": "Feature", "properties": { "fid": "1566", "osm_id": "5189296143", "name": "Mi Casita", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.7040912, -34.664192 ] ] } },
{ "type": "Feature", "properties": { "fid": "1684", "osm_id": "5812721705", "name": "Wakolda", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Merlo\",\"addr:housenumber\"=>\"824\",\"addr:postcode\"=>\"1722\",\"addr:street\"=>\"Córdoba\",\"amenity\"=>\"restaurant\"" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -58.732809, -34.6671771 ] ] } }
]
}
